import User from './api/user/user.model';
import Post from 'api/post/post.model';
import Hashtag from 'api/hashtag/hashtag.model';
import Like from 'api/like/like.model';
import { ActivityType, Activity } from 'api/activity/activity.model';

export var users: User[] = [
    // {
    //     id: "1",
    //     email: "email@gmail.com",
    //     password: "password",
    //     dateCreated: new Date(),
    //     firstName: "Veton",
    //     lastName: "Hajrizi",
    //     birthdate: new Date(1998, 3, 15),
    //     livingIn: "Prishtina",
    //     education: "UBT",
    //     workingAt: "Celonis",
    //     hobby: "table-tennis",
    // },
    // {
    //     id: "2",
    //     email: "email@gmail.com",
    //     password: "password",
    //     dateCreated: new Date(),
    //     firstName: "Jon",
    //     lastName: "Hajrizi",
    //     birthdate: new Date(1998, 3, 15),
    //     livingIn: "Prishtina",
    //     education: "UBT",
    //     workingAt: "Celonis",
    //     hobby: "table-tennis",
    // },
    // {
    //     id: "3",
    //     email: "email@gmail.com",
    //     password: "password",
    //     dateCreated: new Date(),
    //     firstName: "Ermal",
    //     lastName: "Hajrizi",
    //     birthdate: new Date(1998, 3, 15),
    //     livingIn: "Prishtina",
    //     education: "UBT",
    //     workingAt: "Celonis",
    //     hobby: "table-tennis",
    // },
    // {
    //     id: "4",
    //     email: "email@gmail.com",
    //     password: "password",
    //     dateCreated: new Date(),
    //     firstName: "Ilmi",
    //     lastName: "Hajdini",
    //     birthdate: new Date(1998, 3, 15),
    //     livingIn: "Prishtina",
    //     education: "UBT",
    //     workingAt: "Celonis",
    //     hobby: "table-tennis",
    // },
    // {
    //     id: "5",
    //     email: "email@gmail.com",
    //     password: "password",
    //     dateCreated: new Date(),
    //     firstName: "John",
    //     lastName: "Doe",
    //     birthdate: new Date(1998, 3, 15),
    //     livingIn: "Prishtina",
    //     education: "UBT",
    //     workingAt: "Celonis",
    //     hobby: "table-tennis",
    // },
    // {
    //     id: "6",
    //     email: "email@gmail.com",
    //     password: "password",
    //     dateCreated: new Date(),
    //     firstName: "Name",
    //     lastName: "Surname",
    //     birthdate: new Date(1998, 3, 15),
    //     livingIn: "Prishtina",
    //     education: "UBT",
    //     workingAt: "Celonis",
    //     hobby: "table-tennis",
    // },
    // {
    //     id: "7",
    //     email: "email@gmail.com",
    //     password: "password",
    //     dateCreated: new Date(),
    //     firstName: "First",
    //     lastName: "Second",
    //     birthdate: new Date(1998, 3, 15),
    //     livingIn: "Prishtina",
    //     education: "UBT",
    //     workingAt: "Celonis",
    //     hobby: "table-tennis",
    // },
    // {
    //     id: "8",
    //     email: "email@gmail.com",
    //     password: "password",
    //     dateCreated: new Date(),
    //     firstName: "Random",
    //     lastName: "Person",
    //     birthdate: new Date(1998, 3, 15),
    //     livingIn: "Prishtina",
    //     education: "UBT",
    //     workingAt: "Celonis",
    //     hobby: "table-tennis",
    // },
    // {
    //     id: "9",
    //     email: "email@gmail.com",
    //     password: "password",
    //     dateCreated: new Date(),
    //     firstName: "Leo",
    //     lastName: "Messi",
    //     birthdate: new Date(1998, 3, 15),
    //     livingIn: "Prishtina",
    //     education: "UBT",
    //     workingAt: "Celonis",
    //     hobby: "table-tennis",
    // },
    // {
    //     id: "10",
    //     email: "email@gmail.com",
    //     password: "password",
    //     dateCreated: new Date(),
    //     firstName: "James",
    //     lastName: "Smith",
    //     birthdate: new Date(1998, 3, 15),
    //     livingIn: "Prishtina",
    //     education: "UBT",
    //     workingAt: "Celonis",
    //     hobby: "table-tennis",
    // },
    // {
    //     id: "11",
    //     email: "email@gmail.com",
    //     password: "password",
    //     dateCreated: new Date(),
    //     firstName: "Pellumb",
    //     lastName: "Hajdari",
    //     birthdate: new Date(1998, 3, 15),
    //     livingIn: "Prishtina",
    //     education: "UBT",
    //     workingAt: "Celonis",
    //     hobby: "table-tennis",
    // },
    // {
    //     id: "19",
    //     email: "email@gmail.com",
    //     password: "password",
    //     dateCreated: new Date(),
    //     firstName: "Leo",
    //     lastName: "Messi",
    //     birthdate: new Date(1998, 3, 15),
    //     livingIn: "Prishtina",
    //     education: "UBT",
    //     workingAt: "Celonis",
    //     hobby: "table-tennis",
    // },
    // {
    //     id: "13",
    //     email: "email@gmail.com",
    //     password: "password",
    //     dateCreated: new Date(),
    //     firstName: "James",
    //     lastName: "Smith",
    //     birthdate: new Date(1998, 3, 15),
    //     livingIn: "Prishtina",
    //     education: "UBT",
    //     workingAt: "Celonis",
    //     hobby: "table-tennis",
    // },
    // {
    //     id: "14",
    //     email: "email@gmail.com",
    //     password: "password",
    //     dateCreated: new Date(),
    //     firstName: "Pellumb",
    //     lastName: "Hajdari",
    //     birthdate: new Date(1998, 3, 15),
    //     livingIn: "Prishtina",
    //     education: "UBT",
    //     workingAt: "Celonis",
    //     hobby: "table-tennis",
    // },
];

export var posts: Post[] = [
    {
        id: "1",
        postedBy: "1",
        dateCreated: new Date(2018, 4, 2),
        content: "This is my first #social network post!",
    },
    {
        id: "2",
        postedBy: "1",
        dateCreated: new Date(2018, 4, 2),
        content: "Being in social net is so fun! I can become friends with many people of similar interests and spend my time #reading interesting posts",
    },
    {
        id: "3",
        postedBy: "1",
        dateCreated: new Date(2018, 4, 2),
        content: "I like social net's design. It is very easy and intiutive to use.",
    },
    {
        id: "4",
        postedBy: "1",
        dateCreated: new Date(2018, 4, 2),
        content: "This is my first #social network post!",
    },
    {
        id: "5",
        postedBy: "1",
        dateCreated: new Date(2018, 4, 2),
        content: "Being in social net is so fun! I can become friends with many people of similar interests and spend my time #reading interesting posts",
    },
    {
        id: "6",
        postedBy: "1",
        dateCreated: new Date(2018, 4, 2),
        content: "This is my last #social network post!",
    },
    {
        id: "7",
        postedBy: "1",
        dateCreated: new Date(2018, 4, 2),
        content: "I like social net's design. It is very easy and intiutive to use.",
    },
];

export var hashtags: Hashtag[] = [
    {
        id: "1",
        dateCreated: new Date(2018, 4, 2),
        hashtag: "best",
    },
    {
        id: "2",
        dateCreated: new Date(2018, 4, 2),
        hashtag: "best",
    },
    {
        id: "3",
        dateCreated: new Date(2018, 4, 2),
        hashtag: "kjb",
    },
    {
        id: "4",
        dateCreated: new Date(2018, 4, 2),
        hashtag: "bekhyfhst",
    },
    {
        id: "5",
        dateCreated: new Date(2018, 4, 2),
        hashtag: "kjgj",
    },
    {
        id: "6",
        dateCreated: new Date(2018, 4, 2),
        hashtag: "oufg",
    },
    {
        id: "7",
        dateCreated: new Date(2018, 4, 2),
        hashtag: "iuguh",
    },
    {
        id: "8",
        dateCreated: new Date(2018, 4, 2),
        hashtag: "gytfy",
    },
    {
        id: "9",
        dateCreated: new Date(2018, 4, 2),
        hashtag: "tsdfhj",
    },
    {
        id: "10",
        dateCreated: new Date(2018, 4, 2),
        hashtag: "uifugh",
    },
    {
        id: "11",
        dateCreated: new Date(2018, 4, 2),
        hashtag: "ihu",
    },
    {
        id: "12",
        dateCreated: new Date(2018, 4, 2),
        hashtag: "ljguyfdth",
    },
];

export var likes: Like[] = [
    {
        id: "1",
        dateCreated: new Date(),
        likedBy: "1",
        postId: "1",
    },
    {
        id: "2",
        dateCreated: new Date(),
        likedBy: "2",
        postId: "1",
    },
    {
        id: "3",
        dateCreated: new Date(),
        likedBy: "3",
        postId: "1",
    },
    {
        id: "4",
        dateCreated: new Date(),
        likedBy: "4",
        postId: "1",
    },
    {
        id: "5",
        dateCreated: new Date(),
        likedBy: "5",
        postId: "1",
    },
    {
        id: "6",
        dateCreated: new Date(),
        likedBy: "1",
        postId: "1",
    },
    {
        id: "7",
        dateCreated: new Date(),
        likedBy: "2",
        postId: "3",
    },
    {
        id: "8",
        dateCreated: new Date(),
        likedBy: "1",
        postId: "2",
    },
    {
        id: "9",
        dateCreated: new Date(),
        likedBy: "1",
        postId: "2",
    },
    {
        id: "10",
        dateCreated: new Date(),
        likedBy: "1",
        postId: "2",
    },
    {
        id: "11",
        dateCreated: new Date(),
        likedBy: "1",
        postId: "1",
    },
    {
        id: "12",
        dateCreated: new Date(),
        likedBy: "1",
        postId: "2",
    },
    {
        id: "13",
        dateCreated: new Date(),
        likedBy: "1",
        postId: "1",
    },
    {
        id: "14",
        dateCreated: new Date(),
        likedBy: "1",
        postId: "2",
    },
    {
        id: "15",
        dateCreated: new Date(),
        likedBy: "1",
        postId: "1",
    },
    {
        id: "16",
        dateCreated: new Date(),
        likedBy: "1",
        postId: "1",
    },
    {
        id: "17",
        dateCreated: new Date(),
        likedBy: "1",
        postId: "1",
    },
    {
        id: "18",
        dateCreated: new Date(),
        likedBy: "1",
        postId: "1",
    },
    {
        id: "19",
        dateCreated: new Date(),
        likedBy: "1",
        postId: "2",
    },
    {
        id: "21",
        dateCreated: new Date(),
        likedBy: "1",
        postId: "1",
    },
    {
        id: "31",
        dateCreated: new Date(),
        likedBy: "1",
        postId: "1",
    },
    {
        id: "41",
        dateCreated: new Date(),
        likedBy: "1",
        postId: "1",
    },
    {
        id: "51",
        dateCreated: new Date(),
        likedBy: "1",
        postId: "2",
    },
    {
        id: "61",
        dateCreated: new Date(),
        likedBy: "1",
        postId: "1",
    },
    {
        id: "71",
        dateCreated: new Date(),
        likedBy: "1",
        postId: "1",
    },
    {
        id: "81",
        dateCreated: new Date(),
        likedBy: "1",
        postId: "2",
    },
]

export var activities: Activity[] = [
    {
        id: "1",
        dateCreated: new Date(2021, 4, 2),
        commitedBy: "1",
        type: "LIKE",
        targetUser: undefined,
    },
    {
        id: "1",
        dateCreated: new Date(2020, 4, 2),
        commitedBy: "1",
        type: "FRIENDSHIP",
        targetUser: "2",
    },
    {
        id: "1",
        dateCreated: new Date(2019, 4, 2),
        commitedBy: "1",
        type: "LIKE",
        targetUser: undefined,
    },
    {
        id: "1",
        dateCreated: new Date(2018, 4, 2),
        commitedBy: "1",
        type: "LIKE",
        targetUser: undefined,
    },
    {
        id: "1",
        dateCreated: new Date(2017, 4, 2),
        commitedBy: "1",
        type: "LIKE",
        targetUser: undefined,
    },
    {
        id: "1",
        dateCreated: new Date(2016, 4, 2),
        commitedBy: "1",
        type: "LIKE",
        targetUser: undefined,
    },
    {
        id: "1",
        dateCreated: new Date(2015, 4, 2),
        commitedBy: "1",
        type: "LIKE",
        targetUser: undefined,
    },
    {
        id: "1",
        dateCreated: new Date(2014, 4, 2),
        commitedBy: "1",
        type: "LIKE",
        targetUser: undefined,
    },
    {
        id: "1",
        dateCreated: new Date(2013, 4, 2),
        commitedBy: "1",
        type: "LIKE",
        targetUser: undefined,
    },
    {
        id: "1",
        dateCreated: new Date(2012, 4, 2),
        commitedBy: "1",
        type: "LIKE",
        targetUser: undefined,
    },
    {
        id: "1",
        dateCreated: new Date(2011, 4, 2),
        commitedBy: "1",
        type: "LIKE",
        targetUser: undefined,
    },
    {
        id: "1",
        dateCreated: new Date(2010, 4, 2),
        commitedBy: "1",
        targetUser: "2",
        type: "LIKE",
    },
    {
        id: "1",
        dateCreated: new Date(2009, 4, 2),
        commitedBy: "1",
        type: "LIKE",
        targetUser: undefined,
    },
    {
        id: "1",
        dateCreated: new Date(2018, 4, 2),
        commitedBy: "1",
        type: "LIKE",
        targetUser: undefined,
    },
    {
        id: "1",
        dateCreated: new Date(2018, 4, 2),
        commitedBy: "1",
        type: "LIKE",
        targetUser: undefined,
    },
    {
        id: "1",
        dateCreated: new Date(2018, 4, 2),
        commitedBy: "1",
        type: "LIKE",
        targetUser: undefined,
    },
    {
        id: "1",
        dateCreated: new Date(2018, 4, 2),
        commitedBy: "1",
        type: "LIKE",
        targetUser: undefined,
    },
    {
        id: "1",
        dateCreated: new Date(2018, 4, 2),
        commitedBy: "1",
        type: "LIKE",
        targetUser: undefined,
    },
];